test auto-deploy action
EnterpriseDB/docs pull request #1500
Opened 2021-06-21 22:35 UTC by josh-heyer

Quick test to see if netlify draft deployments are good enough for this

2021-07-06 23:36 UTC, frago12 requested changes

2021-07-06 23:36 UTC, frago12 commented on .github/workflows/deploy-draft.yml
> +      run: yarn install --immutable
what do you think about having Yarn installed in the package.json as a dev dependency and then just use it here  `npx yarn install --immutable`?

2021-07-06 23:36 UTC, frago12 commented on .github/workflows/deploy-draft.yml
> +        echo "NETLIFY_DRAFT_URL=`jq -r '.deploy_url' deploy_results.json`" >> $GITHUB_ENV
Same as above, we could add `netlify-cli` as a dev dependency to the package.json or use this other action? https://github.com/marketplace/actions/netlify-actions

2021-07-20 23:23 UTC, josh-heyer commented
Thanks for the suggestions, @frago12 - with that plus a bit of extra care in cache preservation, these are looking a lot shinier!

2021-08-09 21:38 UTC, jericson-edb approved these changes
Looks good! 

I'm thinking we might want to [package some of our action steps](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action) to so that we can avoid duplicating code. (But this is scope creep for now!)

2021-08-09 21:38 UTC, jericson-edb commented on .github/workflows/deploy-draft.yml
> +    - uses: actions/setup-node@v1
I switched to @v2 here.

2021-08-09 23:06 UTC, merged