Adding redirection to EPRS docset
EnterpriseDB/docs pull request #1517
Opened 2021-06-30 17:08 UTC by abhilasha-narendra

## What Changed?

Adding redirection for EPRS HTML set on Docs 1.0 site.

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**
- [ ] This PR adds new content
- [x] This PR changes existing content
- [ ] This PR removes existing content

2021-07-09 23:03 UTC, josh-heyer requested changes

2021-07-09 23:03 UTC, josh-heyer commented on product_docs/docs/eprs/6.2/index.mdx
> +redirects:
should use `legacyRedirects` for these (paths that exist on the old /edb-docs site, not the new /docs site). For details, see: https://github.com/EnterpriseDB/docs/tree/develop/docs/overviews/legacy-redirects#add_legacy_redirectspy

```suggestion
legacyRedirects:
```

2021-07-12 09:45 UTC, drothery-edb approved these changes

2021-07-16 04:14 UTC, josh-heyer approved these changes

2021-07-16 04:14 UTC, merged