Add BDR 4.0
EnterpriseDB/docs pull request #2075
Opened 2021-11-30 19:05 UTC by jericson-edb

## What Changed?

Added BDR 4.0 documentation.

**Content**

- [X] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

2021-11-30 20:14 UTC, dougcalobrisi approved these changes

2021-11-30 20:15 UTC, dougcalobrisi requested changes
Just noticed `<AuthenticatedContentPlaceholder target="https://documentation.2ndquadrant.com/bdr3-enterprise/release/latest/camo/" topic="Eager Replication" />`

I think we need to change that link. Checking.

2021-12-01 18:36 UTC, dougcalobrisi approved these changes

2021-12-01 20:03 UTC, drothery-edb approved these changes
LGTM

2021-12-01 21:14 UTC, merged