Update index.mdx
EnterpriseDB/docs pull request #2212
Opened 2022-01-10 15:17 UTC by ftouserkani-edb

## What Changed?

Please list, at a high level, what changed in your branch. If you changed content, include the product, section, and version as applicable. **Please remove the user instructions including the examples before merging the PR.**

**Examples**

- Fixed typo in EPAS 13 epas_inst_linux guide
- Added more detail to ARK 3.5 getting started guide introduction
- Fixed broken link on `/supported-open-source/pgbackrest/05-retention_policy/` page

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [ ] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

2022-01-10 16:00 UTC, drothery-edb requested changes
We need the developer to review these changes. @ftouserkani-edb , you had a similar PR that I closed per my interpretation of the developer's comments (#2163). IAdded @xugy99 as a reviewer.

2022-01-10 21:53 UTC, ftouserkani-edb commented
Hi Dee Dee,

I have several updates to the documentation that I would like to compile and share.
I would like to know what might be the most efficient way of updating the online documents??

Should I be doing the updates in GitHub action just like I have been doing or conveying  them to someone in your group and/or Dev if you can identify the DEV folks for me ( I can list them as required reviewers in Gtihub).

Could you please advise?


Thanks,


Frank Touserkani
Cloud Support Engineer
***@***.***

+1 781-325-8962
34 Crosby Drive, Suite 210, Bedford, MA 01730, USA



> On Jan 10, 2022, at 11:00 AM, Dee Dee Rothery ***@***.***> wrote:
> 
> 
> @drothery-edb requested changes on this pull request.
> 
> We need the developer to review these changes. @ftouserkani-edb <https://github.com/ftouserkani-edb> , you had a similar PR that I closed per my interpretation of the developer's comments. I'm looking for that PR now.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/EnterpriseDB/docs/pull/2212#pullrequestreview-848009506>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AWQYHF35IGMZOCPMQOS4GOTUVL7BZANCNFSM5LT5HO3Q>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you were mentioned.
>

2022-01-10 22:18 UTC, drothery-edb commented
@ftouserkani-edb , I think raising PRs is great if you suggesting specific changes such as this one. I can help tag the correct developer to review to ensure the changes are technically correct. If you have broader suggestions, you can raise a GitHub issue, email me, or create a Jira ticket.

2022-01-11 14:08 UTC, ftouserkani-edb commented
Great. Thank You.

Frank

On Mon, Jan 10, 2022 at 5:18 PM Dee Dee Rothery ***@***.***>
wrote:

> @ftouserkani-edb <https://github.com/ftouserkani-edb> , I think raising
> PRs is great if you suggesting specific changes such as this one. I can
> help tag the correct developer to review to ensure the changes are
> technically correct. If you have broader suggestions, you can raise a
> GitHub issue, email me, or create a Jira ticket.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EnterpriseDB/docs/pull/2212#issuecomment-1009398131>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWQYHFYHMXTZNZAM2MCPQMTUVNLKXANCNFSM5LT5HO3Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-13 14:57 UTC, gsong commented
@drothery-edb Per <https://github.com/EnterpriseDB/docs/pull/2163#issuecomment-1012118409>, this change looks fine to me.

2022-01-13 15:02 UTC, gsong commented
@drothery-edb As a side note, we should probably show the customer how to find `region`, `instance-type`, and `endpoint` options:

```sh
$ curl -sL https://raw.githubusercontent.com/EnterpriseDB/cloud-utilities/main/azure/biganimal-preflight-azure | bash -s

Usage: biganimal-preflight-azure [options] <target-subscription> <region>

Arguments:
    <target-subscription>    Azure subscription for BigAnimal deployment
    <region>                 Azure region for BigAnimal deployment

Options:
    -h, --help               Print this help message
    -i, --instance-type      Azure VM instance for BigAnimal cluster, e.g., e2s_v3
    -a, --high-availability  Plan for BigAnimal cluster with high availability enabled
    -e, --endpoint           Network endpoint flavor for BigAnimal cluster
    -r, --activate-region    Include region activation, if no clusters exist in region
    --onboard                Check if the user and subscription are configured appropriately

Behavior defaults to --onboard if no other options provided.

Examples:
    biganimal-preflight-azure --onboard 12412ab3d-1515-2217-96f5-0338184fcc04 eastus2
    biganimal-preflight-azure -i e2s_v3 --high-availability -e private 12412ab3d-1515-2217-96f5-0338184fcc04 eastus2

Available regions are: australiaeast brazilsouth canadacentral centralus eastus eastus2 francecentral japaneast northeurope norwayeast southcentralus southeastasia uksouth westeurope westus2 westus3
Available instance types are: e2s_v3 e4s_v3 e8s_v3 e16s_v3 e20s_v3 e32s_v3 e48s_v3 e64s_v3
Available endpoint flavors: public private
```

2022-01-13 15:14 UTC, ftouserkani-edb commented on product_docs/docs/biganimal/release/getting_started/01_preparing_azure/index.mdx
> +      <subscription-ID> <azure-region> \
Absolutely. Matching the script 'usage' output and aligning it with the UI is desirable.

2022-01-13 15:29 UTC, gsong commented on product_docs/docs/biganimal/release/getting_started/01_preparing_azure/index.mdx
> +      <subscription-ID> <azure-region> \
@ftouserkani-edb Do you want to go ahead and make those changes, either in this PR or as a separate PR?

2022-01-13 15:29 UTC, gsong commented
@xugy99 @ftouserkani-edb What's the best way to ensure that docs is kept up to date as the script evolves?

2022-01-13 16:32 UTC, drothery-edb commented
Merging these changes and created an issue to track additional changes the doc team plans to make per the suggestions on this PR: https://github.com/EnterpriseDB/docs/issues/2227

2022-01-13 16:32 UTC, merged