Update index.mdx
EnterpriseDB/docs pull request #3068
Opened 2022-08-19 15:20 UTC by ftouserkani-edb

BigAnimal free trial users keep going around in circles attempting to log in to BigAnimal portal.
This PR tends to clear that confusion and point the free trial users to the correct sute when attempting to login into the portal.   

Grammatical updates are left to the discretion of the documentation folks.

- [ ] This PR adds new content
- [x] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

2022-08-23 14:14 UTC, ebgitelman requested changes

2022-08-23 14:14 UTC, ebgitelman commented on product_docs/docs/biganimal/release/free_trial/detail/create_an_account/index.mdx
> +You will need to register with EDB in order to access BigAnimal free trial, as well as EDB's training and software downloads.
You need to register with EDB to access the BigAnimal free trial and EDB's training and software downloads.

(no future tense, "in order to" is wordy)

2022-08-23 14:14 UTC, ebgitelman commented on product_docs/docs/biganimal/release/free_trial/detail/create_an_account/index.mdx
> +3. Fill in the form, and agree to the **Terms and Conditions** and the **Privacy Policy**.
Select **Test drive for free**.
Fill in the form, and agree to the terms and conditions and privacy policy.

2022-08-23 14:14 UTC, ebgitelman commented on product_docs/docs/biganimal/release/free_trial/detail/create_an_account/index.mdx
> +6. Click the activation link and enter a password for your EDB account.
Select was correct. Discard this edit.

2022-08-23 14:14 UTC, ebgitelman commented on product_docs/docs/biganimal/release/free_trial/detail/create_an_account/index.mdx
> +    Please continue to use this portal in order to access BigAnimal for the duration of your free trial.
If you already signed up for an EDB account, navigate to <https://freetrial.biganimal.com/>  to log in. Continue to use this portal to access BigAnimal for the rest of your free trial.

2022-08-23 14:14 UTC, ebgitelman commented on product_docs/docs/biganimal/release/free_trial/detail/create_an_account/index.mdx
>  5. Check your email. You should receive an email from EDB containing an activation link.
Check your email for an email from EDB that contains an activation link.

2022-08-25 10:56 UTC, drothery-edb approved these changes

2022-08-25 10:57 UTC, merged