Add release notes for PGD 4.2.1
EnterpriseDB/docs pull request #3308
Opened 2022-11-03 17:35 UTC by irionr

BDR-2785

## What Changed?
Release notes for PGD 4.2.1

2022-11-10 12:08 UTC, mwanner requested changes

2022-11-10 12:08 UTC, mwanner commented on product_docs/docs/pgd/4/rel_notes/pgd_4.2.1_rel_notes.mdx
> +| BDR       | 4.2.1   | Bug fix | Add maintanance to bdr.queue catalog table (BDR-2475, RT84105) <p> Remove automatically rows older than the `bdr.max_queue_days` (default disabled) on bdr.queue. </p
s/Remove automatically/Automatically remove/

I would be more explicit with the default and add a separate sentence: "By default, entries are retained forever to match the existing behaviour."

2022-11-10 12:08 UTC, mwanner commented on product_docs/docs/pgd/4/rel_notes/pgd_4.2.1_rel_notes.mdx
> +| BDR       | 4.2.1   |         | Abort unresolved commit scope transactions on node part (BDR-2597) <p> Add a new peer state PART_TX_RESOLVE. This state will abort any remaining unresolved group com
Let's mark these two as "Bug fix" as well, please.

2022-11-10 13:34 UTC, mwanner approved these changes
LGTM

2022-11-17 10:00 UTC, drothery-edb commented on product_docs/docs/pgd/4/rel_notes/pgd_4.2.1_rel_notes.mdx
> +| BDR       | 4.2.1   | Bug fix | Use two_phase slots in `bdr_init_physical` on PG14+ () <p> Improve prepared transaction handling during `bdr_init_physical`. </p>
```suggestion
| BDR       | 4.2.1   | Bug fix | Use two_phase slots in `bdr_init_physical` on PG14+ () <p> Improve prepared transaction handling during `bdr_init_physical`. </p>                                                                                                                                                                                        |
```
Is there a bug number for this? If not, let's remove the parens.

2022-11-17 10:14 UTC, drothery-edb commented on product_docs/docs/pgd/4/rel_notes/pgd_4.2.1_rel_notes.mdx
> +| BDR       | 4.2.1   | Bug fix | Use two_phase slots in `bdr_init_physical` on PG14+ () <p> Improve prepared transaction handling during `bdr_init_physical`. </p>
updated the landing page for release notes. Please review and update the date and versions, if needed

2022-11-17 11:06 UTC, irionr commented on product_docs/docs/pgd/4/rel_notes/pgd_4.2.1_rel_notes.mdx
> +| BDR       | 4.2.1   | Bug fix | Use two_phase slots in `bdr_init_physical` on PG14+<p> Improve prepared transaction handling during `bdr_init_physical`. </p>
Is the space needed after `PG14+` ?

2022-11-17 13:19 UTC, irionr commented on product_docs/docs/pgd/3.6/release-notes.mdx
>  ## BDR 3.6.2 (2022 Aug 23)
I see there is an issue with the previous release, it should be `3.6.32`, not `3.6.2`

2022-11-17 13:44 UTC, drothery-edb approved these changes

2022-11-17 13:44 UTC, merged