PEM online help - removed duplicate topics
EnterpriseDB/docs pull request #3316
Opened 2022-11-07 12:48 UTC by nidhibhammar

2022-11-07 13:41 UTC, drothery-edb approved these changes

2022-11-07 13:47 UTC, sonotley requested changes
The deleted version of the config params page still appears in search and then gives a 404 if I click it (perhaps this is just a cache issue or something?)

2022-11-07 19:23 UTC, drothery-edb commented
> The deleted version of the config params page still appears in search and then gives a 404 if I click it (perhaps this is just a cache issue or something?)

@josh-heyer a deleted topic shouldn't appear in search results once it is deployed to production, correct?

2022-11-08 10:59 UTC, merged

2022-11-08 19:14 UTC, josh-heyer commented
Correct, @drothery-edb. Draft deploys don't generate their own search index (would slow down deployment), so you get whatever results would currently appear in production when searching on these - that means any new content doesn't show up, and removed content does (but will produce a 404 when attempting to view).