EPAS: data type topic - index approach prototype
EnterpriseDB/docs pull request #3405
Opened 2022-12-01 20:57 UTC by drothery-edb

## What Changed?

2023-01-10 10:11 UTC, drothery-edb commented
Fixes https://github.com/EnterpriseDB/docs/issues/3115

2023-04-18 14:30 UTC, ebgitelman reviewed
See suggested revision.

2023-04-18 14:30 UTC, ebgitelman commented on product_docs/docs/epas/14/epas_compat_reference/02_the_sql_language/02_data_types/index.mdx
This table lists all the Oracle data types and provides information for each data type. This information includes whether:
- The data type applies to Postgres databases.
- EDB Postgres Advanced Server offers a compatible replacement for the Oracle data types that don't have a suitable equivalent in PostgreSQL. The description includes a link to the implementation details in the EDB Postgres Advanced Server documentation.
- EDB Postgres Advanced Server provides synonyms for PostgreSQL types that you can use in place of the equivalent Oracle type. The description includes a link to the implementation details in the PostgreSQL documentation.

2023-05-23 03:54 UTC, nidhibhammar commented on product_docs/docs/epas/15/epas_compat_reference/02_the_sql_language/02_data_types/index.mdx
> +| `ROWID`             | [`ROWID`](01_numeric_types)            | The EPAS `ROWID` data type that maps to Oracle's `ROWID` data type. It is a custom data type of EPAS and isn't available in PostgreSQL
ROWID is available in both Postgres and Oracle mode

2023-08-11 08:45 UTC, nidhibhammar commented on product_docs/docs/epas/15/reference/sql_reference/02_the_sql_language/02_data_types/array_types.mdx
> +| `ARRAY` | ✅ |     | An alternative syntax to define one-dimensional arrays. |
We can't write ARRAY like this as this may get misinterpreted as a data type. We can skip the table for this data type.

2023-08-11 08:46 UTC, nidhibhammar commented on product_docs/docs/epas/15/reference/sql_reference/02_the_sql_language/02_data_types/composite_types.mdx
> +| --------- | ------ | ----- | --------------------------------------------- |
We can skip the table for composite data type as well

2023-08-17 04:24 UTC, nidhibhammar requested changes
I have left comments to be addressed.

2023-08-22 12:14 UTC, closed without merging

2023-08-22 12:15 UTC, drothery-edb commented
Merged into #4661