Add release notes for PGD 4.3.0
EnterpriseDB/docs pull request #3624
Opened 2023-02-08 16:32 UTC by irionr

BDR-3181

## What Changed?

Add Release notes for BDR 4.3.0

2023-02-08 16:43 UTC, PJMODOS commented on product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
> +| BDR       | 4.3.0   | Feature | Add node_kind to bdr.node <p> We can check the bdr.node what is the kind of a node </p> |
I would not call it feature but rather "Upgrade support"

2023-02-08 16:44 UTC, PJMODOS commented on product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
> +| BDR       | 4.3.0   | Feature | Implement bdr.alter node_kind() <p> Function to change a node kind </p> |
This does not need separate These two just enable the autopatition leader thing so I would not mentione them separately

2023-02-08 16:47 UTC, PJMODOS commented on product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
> +
I'd also add another bug fix - "Fix watermark handling on clusters with multiple sub-groups. <p>Watermark is used to ensure data consistency during join. Previously, this didn't work correctly in the presence of multiple data sub-groups.</p>

or some such

2023-02-08 16:51 UTC, PJMODOS commented on product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
> +
Also another feature is missing  - "Don't allow switching to CAMO Local Mode if the node is not a write lead. <p>In CAMO only one node should be allowed to switch to the Local Mode at given time. We now require the node to be the HARP write leader in order to ensure that rule.</p>

2023-02-08 16:51 UTC, PJMODOS requested changes
Added some requested changes inline

2023-02-13 16:53 UTC, mwanner approved these changes

2023-02-13 17:00 UTC, merged