Add document for Table access methods.
EnterpriseDB/docs pull request #3654
Opened 2023-02-14 01:36 UTC by rakhi-grover

Please review document changes for Table Access methods.

2023-02-14 17:11 UTC, mwanner requested changes

2023-02-14 18:06 UTC, rakhi-grover commented on product_docs/docs/pgd/5/bdr/appusage.mdx
> +need to be cofigured on each participating node in the PGD cluster.
Updated the doc, please check.

2023-02-15 12:53 UTC, mwanner requested changes
Okay, sounds good content wise. Please apply some Markdown formatting (sub-title, check the list, not sure if numbering works) and wrap lines at column 80.

2023-02-15 14:48 UTC, rakhi-grover commented
> Okay, sounds good content wise. Please apply some Markdown formatting (sub-title, check the list, not sure if numbering works) and wrap lines at column 80.

done. Thanks!

2023-02-16 07:46 UTC, mwanner approved these changes

2023-02-16 08:33 UTC, merged