BigAnimal: WALs
EnterpriseDB/docs pull request #3759
Opened 2023-03-02 16:09 UTC by drothery-edb

## What Changed?

2023-03-08 16:33 UTC, amrita-suresh requested changes

2023-03-08 16:33 UTC, amrita-suresh commented on product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
> +       - For Azure,
you can provision a WAL volume for both Azure and AWS clusters. I see now that the designs only include Azure examples; this is an error. Both CSPs should be supported here.

2023-03-08 16:33 UTC, amrita-suresh commented on product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
> +   | Write-ahead logs (WALs)                              | Cluster Settings    | If you are using Azure, you can add a dedicated WAL volume to an existing single node, high availability, or faraway
same thing, AWS is also supported here.

2023-10-12 09:33 UTC, djw-m commented
This feature is reported as blocked/on hold till 2024. Closing this ticket for now.

2023-10-12 09:33 UTC, closed without merging