DF-325-Removing redundant topics from the docs website PEM online help
EnterpriseDB/docs pull request #3787
Opened 2023-03-15 04:17 UTC by arup-roy2023

## What Changed?
Updated link in the following files:
index.mdx
pem_architecture.mdx

2023-04-06 09:27 UTC, nidhibhammar commented on product_docs/docs/pem/8/managing_pem_agent.mdx
> +- /pem/latest/pem_online_help/04_toc_pem_features/16_pem_scheduled_jobs/
Why this redirect is in version 8. We don't have this topic in version 9?

2023-04-11 05:20 UTC, nidhibhammar commented on product_docs/docs/pem/9/pem_connecting_to_database_server.mdx
>  > -   Use the `Password` field to provide the password of the user that is associated with the defined server.
```suggestion
-   Use the `Password` field to provide the user's password associated with the defined server.
```

2023-04-11 05:22 UTC, nidhibhammar commented on product_docs/docs/pem/9/pem_connecting_to_database_server.mdx
>  > -   Check the box next to `Save Password` to instruct the server to save the password for future connections; if you save the password, you will not be prompted when reconnecting to the database se
```suggestion
-   Select the box next to `Save Password` to instruct the server to save the password for future connections. If you save the password, you are not prompted while reconnecting to the database server with this server definition.
```

2023-04-17 08:23 UTC, nidhibhammar commented on product_docs/docs/pem/8/managing_pem_agent.mdx
> +- /pem/latest/pem_online_help/04_toc_pem_features/16_pem_scheduled_jobs/
Added to v9

2023-04-19 10:46 UTC, drothery-edb commented on product_docs/docs/pem/9/in_app_help.mdx
> +The in-app help provides comprehensive details about the PEM web interface, including the menu items, charts and graphs on the dashboards, and the options on the dialog boxes. The in-app help also in
Databases should be singular in all of these sections.
```suggestion
The in-app help provides comprehensive details about the PEM web interface, including the menu items, charts and graphs on the dashboards, and the options on the dialog boxes. The in-app help also includes instructions for creating database objects.
```

2023-04-19 11:41 UTC, drothery-edb submitted a review, later dismissed

2023-04-20 02:41 UTC, josh-heyer requested changes
The following existing paths fail to load or redirect in this branch: 

```
/pem/latest/pem_online_help/01_toc_pem_getting_started/05_group_dialog/
/pem/latest/pem_online_help/01_toc_pem_getting_started/11_connect_error/
/pem/latest/pem_online_help/02_toc_pem_agent/04_pem_agent_ha/
/pem/latest/pem_online_help/03_toc_pem_client/02_pem_toolbar/
/pem/latest/pem_online_help/03_toc_pem_client/04_preferences/
/pem/latest/pem_online_help/03_toc_pem_client/05_keyboard_shortcuts/
/pem/latest/pem_online_help/03_toc_pem_client/06_search_objects/
/pem/latest/pem_online_help/04_toc_pem_features/
/pem/latest/pem_online_help/05_toc_pem_management_basics/10_managing_cluster_objects/
/pem/latest/pem_online_help/06_toc_pem_bart_management/07_bart_backup_dialog/
/pem/latest/pem_online_help/08_toc_pem_developer_tools/
/pem/latest/pem_online_help/08_toc_pem_developer_tools/01_debugger/
/pem/latest/pem_online_help/08_toc_pem_developer_tools/03_pem_interpreting_graphical_query/
/pem/latest/pem_online_help/08_toc_pem_developer_tools/04_editgrid/
/pem/latest/pem_online_help/08_toc_pem_developer_tools/04_editgrid/01_viewdata_filter/
/pem/latest/pem_online_help/10_pgagent/
/pem/latest/pem_online_help/10_pgagent/01_using_pgagent/
/pem/latest/pem_online_help/10_pgagent/02_pgagent_install/
/pem/latest/pem_online_help/10_pgagent/03_pgagent_jobs/
/pem/latest/pem_online_help/10_pgagent/04_pgagent-steps/
/pem/latest/pem_online_help/10_pgagent/05_pgagent-schedules/
/pem/latest/pem_online_help/11_appendices/
/pem/latest/pem_online_help/11_appendices/01_licence/
/pem/latest/pem_online_help/11_appendices/02_kerberos/
/pem/latest/pem_online_help/11_appendices/03_openssl/
/pem/latest/pem_online_help/11_appendices/04_snmp++/
/pem/latest/pem_online_help/11_appendices/05_jquery_table_sort/
```

To avoid 404s, please ensure these are redirected to something sensible.

2023-04-20 09:44 UTC, drothery-edb approved these changes

2023-04-20 09:46 UTC, merged