Patroni: correction from copy edit - code block adjustments
EnterpriseDB/docs pull request #3892
Opened 2023-04-05 09:54 UTC by drothery-edb

## What Changed?

Clarified edit related to listening on ports
Removed prompt from code blocks so that the contents can be copied and pasted in a terminal and work

2023-05-23 15:20 UTC, martinmarques commented
Dee Dee can the same code block be applied to the rest of the documentation before merging? Right now it only applies to "Managing a cluster" and not the the quick starts or "Patroni" and "Etcd" installation instructions

2023-05-24 20:30 UTC, drothery-edb commented
@martinmarques I ran into two issues trying to apply the code block output formatting: you can't have commands in a code block after output and the __OUTPUT__ markup was not being interpreted correctly after cat << commands. For both of these issues I ended up splitting up the code blocks. I'm not sure if you will find the workaround acceptable. You can decide for yourself by looking at these topics after the draft deploy complete:

- https://deploy-preview-3892--edb-docs-staging.netlify.app/docs/supported-open-source/patroni/debian11_quick_start/
- https://deploy-preview-3892--edb-docs-staging.netlify.app/docs/supported-open-source/patroni/installing_etcd/

Let me know what you think.

2023-05-31 16:58 UTC, martinmarques requested changes
Besides the missing removal of one `$`, we also need to apply the same to the Patroni installation instructions and the "Tips and FAQ"

2023-05-31 16:58 UTC, martinmarques commented on advocacy_docs/supported-open-source/patroni/rhel8_quick_start.mdx
>  $ psql -U admin -d postgres -h pg-patroni1 -p 5001 -c "SELECT pg_is_in_recovery();"
Need to remove the `$` here as well

2023-06-01 08:10 UTC, djw-m commented on advocacy_docs/supported-open-source/patroni/rhel8_quick_start.mdx
>  $ psql -U admin -d postgres -h pg-patroni1 -p 5001 -c "SELECT pg_is_in_recovery();"
Fixed in last commit

2023-06-01 13:11 UTC, martinmarques approved these changes

2023-06-01 13:12 UTC, merged