Update functions.mdx
EnterpriseDB/docs pull request #3910
Opened 2023-04-11 14:56 UTC by wind39

Providing node kind options for the `bdr.alter_node_kind()` function.

## What Changed?

2023-04-11 21:00 UTC, drothery-edb commented on product_docs/docs/pgd/5/functions.mdx
> +-   `node_kind` &mdash; Kind of the node, which can be one of: `data`, `standby`, `witness` or `subscriber-only`.
```suggestion
-   `node_kind` &mdash; Kind of the node, which can be one of: `data`, `standby`, `witness`, or `subscriber-only`.
```

2023-04-11 21:21 UTC, djw-m requested changes
Cross referencing the end of the file:

bdr.node_kind_name
Return human friendly name of the node kind (standalone|data|standby|witness|subscriber-only)

Suggests that `standalone` is either an option or should be called out as not an option.

2023-04-14 15:52 UTC, drothery-edb approved these changes

2023-04-14 15:56 UTC, drothery-edb commented
@djw-m is this ready to be merged?

2023-04-14 16:02 UTC, djw-m approved these changes

2023-04-14 16:02 UTC, merged