Add release notes and compatibility info for LC 2.5 release
EnterpriseDB/docs pull request #4036
Opened 2023-05-05 11:36 UTC by sonotley

## What Changed?

Added release notes for LC 2.5

I have added PG15 and PGD5 to the table of supported software.

I have also removed BDR where it is used as a product name for what is
now called EDB Postgres Distributed. Uses of bdr in variables or
database objects are still correct so have been left.

2023-05-05 11:54 UTC, drothery-edb commented
@sonotley, jfyi @ebgitelman has opened another [PR](https://github.com/EnterpriseDB/docs/pull/4029) where she is doing a copy edit and rebranding to PGD.

2023-05-05 13:02 UTC, wind39 requested changes
Looks good, only 1 minor typo.

2023-05-05 13:22 UTC, sonotley commented
> @sonotley, jfyi @ebgitelman has opened another [PR](https://github.com/EnterpriseDB/docs/pull/4029) where she is doing a copy edit and rebranding to PGD. @dougcalobrisi had requested our assistance with the rebranding.

Ok, this PR needs to go out for the release on Tuesday so we can resolve conflicts after that. I knew Doug reached out but didn;t know work had started.

2023-05-05 13:22 UTC, sonotley commented on product_docs/docs/livecompare/2/bdr_support.mdx
> +LiveCompare can be used against EDB Postgres Distributed (PGD, formerly know as BDR)
```suggestion
LiveCompare can be used against EDB Postgres Distributed (PGD, formerly known as BDR)
```

2023-05-09 08:18 UTC, nidhibhammar submitted a review, later dismissed

2023-05-09 09:37 UTC, drothery-edb commented on product_docs/docs/livecompare/2/bdr_support.mdx
> +-   PGD 1, 2, 3, 4 and 5;
Not sure we want to list v1 and v2, but we can deal with that later

2023-05-09 10:50 UTC, drothery-edb commented on product_docs/docs/livecompare/2/supported_technologies.mdx
> +| EDB Postgres Distributed       | 1, 2, 3, 4 and 5                   | Initial, Data and/or Output |
again, I'm not sure we want to include 1 and 2 - we have no docs for those versions

2023-05-09 14:44 UTC, drothery-edb approved these changes

2023-05-09 14:44 UTC, merged