BigAnimal: Google Cloud Provider
EnterpriseDB/docs pull request #4191
Opened 2023-06-05 16:52 UTC by drothery-edb

## What Changed?

https://enterprisedb.atlassian.net/browse/UPM-15351

Related PRs:
GCP regions: https://github.com/EnterpriseDB/docs/pull/4195 - hasn't been reviewed but is merged
Preparing your GCP account: https://github.com/EnterpriseDB/docs/pull/4302 - reviewed and merged
Cluster networking architecture for GCP: https://github.com/EnterpriseDB/docs/pull/4320 - merged but needs review from Jason
Customizing compliance: https://github.com/EnterpriseDB/docs/pull/4327 - merged but needs review from Jason
GCP BAH: https://github.com/EnterpriseDB/docs/pull/4429 - merged - not reviewed updated regions based on UI 7/28

2023-07-06 20:10 UTC, drothery-edb commented
@amrita-suresh do we want to add a note that PGD clusters aren't supported?

2023-07-07 12:29 UTC, amrita-suresh commented
> @amrita-suresh do we want to add a note that PGD clusters aren't supported?

I would defer to @nstott who is looking into whether the PGD issues can be fixed soon

2023-07-19 20:45 UTC, amrita-suresh requested changes

2023-07-19 20:45 UTC, amrita-suresh commented on product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_gcp.mdx
> +1. If the following readiness checks aren't met for your cloud service provider, see [Configure your Google Cloud account](/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/#co
is the AWS link here intentional?

2023-07-19 20:45 UTC, amrita-suresh commented on product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx
> +    | `-i` or `--instance-type` | Google Cloud instance type for the BigAnimal cluster. The help command provides a list of possible VM instance types. Choose the instance type that best suits your a
we won't support C2D or any accelerator optimized instance types at launch. only the instance types that have a "Yes" in column K here: https://docs.google.com/spreadsheets/d/1WWBAEgJjVWwSIKBoU8z4rIt3x1p8pXMMn7JkahWtYxQ/edit#gid=1228767107
and the general purpose instance families we support at MVP will be E2, N2, and N2D - not m5 or m6i, those are AWS volumes

2023-07-19 20:45 UTC, amrita-suresh commented on product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/understanding_quotas_in_gcp.mdx
> +Any time a new VM is deployed in Azure, the vCPUs for the VMs must not exceed the total vCPU limits for the region.
is there a google cloud version of this section yet?

2023-07-19 20:45 UTC, amrita-suresh commented on product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
> +### Google Cloud regions
the regions in NA are not correct; see column F here: https://docs.google.com/spreadsheets/d/1FQiRA-OIzX8CWchY1UGxgJvIblUIf5Ie5SSF2FJ_bOE/edit#gid=830197369
currently BAH+GCP supports N Virginia, Belgium, Sydney, Mumbai regions with more coming soon

2023-07-20 11:18 UTC, merged