Edits to PGD 5 release content
EnterpriseDB/docs pull request #4271
Opened 2023-06-20 15:25 UTC by ebgitelman

Edits to Using TPA topic

2023-06-21 13:47 UTC, djw-m requested changes
Just some notes on within over in when talking about inclusive sets and establishing essentiality where "must" is a little soft.

2023-06-21 13:47 UTC, djw-m commented on product_docs/docs/pgd/5/routing/raft/index.mdx
> +For certain operations in the top-level group, a Raft leader must be both established and connected. Examples of these operations include adding and removing nodes and allocating ranges for [galloc](
```suggestion
For certain operations in the top-level group, it is essential that a Raft leader must be both established and connected. Examples of these operations include adding and removing nodes and allocating ranges for [galloc](../../sequences/#pgd-global-sequences) sequences.
```

2023-06-23 15:01 UTC, drothery-edb submitted a review, later dismissed

2023-06-23 17:33 UTC, drothery-edb approved these changes

2023-06-23 17:33 UTC, merged