Transporter: install templates
EnterpriseDB/docs pull request #4379
Opened 2023-07-10 13:47 UTC by drothery-edb

## What Changed?

2023-07-12 18:31 UTC, dwicinas commented
@drothery-edb Finally ready for your review. Some outstanding questions:

2023-07-14 09:32 UTC, jperozoa reviewed
I think you started this branch from a previous version of the "docs/transporter/preview-content", maybe you can rebase your branch onto "docs/transporter/preview-content" to get the latest changes (for example, changed the path of the docs from version 2 to 2_preview)

2023-07-16 19:50 UTC, drothery-edb commented
> I think you started this branch from a previous version of the "docs/transporter/preview-content", maybe you can rebase your branch onto "docs/transporter/preview-content" to get the latest changes (for example, changed the path of the docs from version 2 to 2_preview)

Could you resolve the conflicts (I think both changes in the conflicts should be accepted) in docs/transporter/preview-content and bring in the latest changes from develop before we rebase this branch? Thanks.

2023-07-17 10:02 UTC, jperozoa commented
> > I think you started this branch from a previous version of the "docs/transporter/preview-content", maybe you can rebase your branch onto "docs/transporter/preview-content" to get the latest changes (for example, changed the path of the docs from version 2 to 2_preview)
> 
> Could you resolve the conflicts (I think both changes in the conflicts should be accepted) in docs/transporter/preview-content and bring in the latest changes from develop before we rebase this branch? Thanks.

@drothery-edb, it's done

2023-07-20 08:06 UTC, jperozoa commented
> * HEL 9



> @jperozoa and @djw-m, There's a few issues to be confirmed in this PR:
> 
> * Are the install commands correct for each platform?
> * Are we now supporting RHEL 9? Easy to add if we are.
> * For ease of reference, I left the old instructions under the Installing directory. I'll remove the old topics as we move closer to a final draft.

@dwicinas I think all the install commands are OK. So far we don't support RHEL 9 (we didn't test it) but in future versions we will add it.

2023-07-24 11:24 UTC, jperozoa requested changes
there are 2 files changed under pge product doc. Those changes should be under transporter

2023-07-24 11:24 UTC, jperozoa commented on product_docs/docs/pge/2/installing/linux_ppc64le/index.mdx
this should be under the transporter product instead of pge

2023-07-24 11:24 UTC, jperozoa commented on product_docs/docs/pge/2_preview/installing/linux_ppc64le/index.mdx
this should be under the transporter product instead of pge

2023-07-24 12:32 UTC, dwicinas commented on product_docs/docs/pge/2/installing/linux_ppc64le/index.mdx
Removed. Thanks for catching this.

2023-07-24 12:33 UTC, dwicinas commented on product_docs/docs/pge/2_preview/installing/linux_ppc64le/index.mdx
removed

2023-07-24 12:33 UTC, jperozoa approved these changes
lgtm

2023-07-24 12:52 UTC, merged