Fixing conflicts docs to reflect actual update/delete behavior
EnterpriseDB/docs pull request #4632
Opened 2023-08-15 13:04 UTC by djw-m

## What Changed?

After viewing the code path, I have determined this is the current behaviour (line 213-221).

Discussion about whether this behaviour is good is out of scope for this change. This just seeks to match observed functionality.

2023-08-15 13:34 UTC, drothery-edb approved these changes

2023-08-24 11:14 UTC, LenzGr commented on product_docs/docs/pgd/5/consistency/conflicts.mdx
> +When using the default, [origin conflict detection](#origin-conflict-detection) and only primary keys for replication, no conflict is detected, leading to the `DELETE` being applied and the row being
```suggestion
When using [origin conflict detection](#origin-conflict-detection) (the default) and only primary keys for replication, no conflict is detected, leading to the `DELETE` being applied and the row being removed. 
```

2023-08-25 08:12 UTC, PJMODOS commented on product_docs/docs/pgd/5/consistency/conflicts.mdx
> +If `REPLICA IDENTITY FULL` is being used for replication, the conflict will be detected and a `delete_recently_updated` conflict is generated.
This is not accurate

2023-08-25 08:13 UTC, PJMODOS commented on product_docs/docs/pgd/5/consistency/conflicts.mdx
> +If `REPLICA IDENTITY FULL` is being used for replication, the conflict will be detected and a `delete_recently_updated` conflict is generated.
The conflict is detected when REPLICA IDENTITY FULL is used and one of the following things are true:
- table uses row version conflict detection/resolution (this anyway requires REPLICA IDENTITY FULL)
- table uses per-column conflict detection/resolution aka CLCD (this anyway requires REPLICA IDENTITY FULL)
- table uses custom conflict resolution triggers

2023-08-25 08:14 UTC, PJMODOS requested changes
See comment inline

2023-08-25 09:04 UTC, djw-m commented
I refer back to the original Jira ticket which reports that this isn’t the
case - if this is in fact a bug or user error, we would appreciate dev
triage before it gets to requests for documentation changes.

On Fri, 25 Aug 2023 at 09:14, Petr Jelinek ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> See comment inline
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EnterpriseDB/docs/pull/4632#pullrequestreview-1595182067>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6E5CBYLTP5JD5NEGYWPRILXXBNGLANCNFSM6AAAAAA3RBMIVI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-04-10 14:48 UTC, closed without merging

2024-04-10 14:48 UTC, josh-heyer commented
Closing this unless / until someone wants to collaborate on it.