BigAnimal: CLI updates for 3.1
EnterpriseDB/docs pull request #4824
Opened 2023-09-12 18:50 UTC by francoughlin

## What Changed?

Updated BigAnimal PGD CLI commands for version 3.1

2023-09-12 20:13 UTC, drothery-edb approved these changes

2023-10-05 17:04 UTC, edbamolvyavahare commented on product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
> +  - provider: azure
both data groups must also have `customMaintenanceWindow` fields defined in the example

2023-10-05 17:07 UTC, edbamolvyavahare requested changes
- both data groups must also have customMaintenanceWindow fields defined in the example
- Rename High Availability -> Primary/Standby High Availability at all places

2023-10-12 09:00 UTC, nidhibhammar commented
@edbamolvyavahare, please review the updates and let us know if any further changes are required or we are good to publish?

2023-11-01 09:04 UTC, edbamolvyavahare approved these changes
LGTM

2023-11-03 04:51 UTC, merged