Update step02-backup-setup.mdx
EnterpriseDB/docs pull request #4938
Opened 2023-10-20 14:09 UTC by sergico

fix to .pgpass template 
- using `*` instead of `replication` does not work as we receive the following errors:
```
connection to server at "192.168.1.20", port 5432 failed: fe_sendauth: no password supplied
```

## What Changed?

2024-09-03 07:37 UTC, gvasquezvargas commented
@sergico  could you please take a look at @piano35-edb 's feedback, so we can get this ready and merge? 🙏

2024-09-30 07:58 UTC, gvasquezvargas commented
@sergico since this branch is a fork, we cannot check it out to implement the changes @piano35-edb  suggested. Do you mind making the corrections and tagging us to merge? Thanks!

2024-10-01 09:45 UTC, sergico commented
@gvasquezvargas I should have missed the previous notifications from github, sorry about that.
Will update the pull request, hopefully today
Ciao e grazie

2024-10-01 15:59 UTC, martinmarques requested changes

2024-10-01 15:59 UTC, martinmarques commented on advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
> +Each line in the `.pgpass` file need to follow below format:
```suggestion
Each line in the `.pgpass` file needs to follow below format:
```

2024-10-01 16:23 UTC, piano35-edb approved these changes

2024-10-01 16:32 UTC, martinmarques approved these changes

2024-10-02 07:41 UTC, gvasquezvargas commented on advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
> +Also note that the database name [db_name] for the barman streaming user MUST be `replication`
```suggestion
The database name [db_name] for the barman streaming user must be `replication`
```

2024-10-02 07:42 UTC, gvasquezvargas commented on advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
> +**Note the change in permissions** - this is necessary to protect the visibility of the file, and PostgreSQL will not use it unless permissions are restricted.
```suggestion
**Note the change in permissions** - this is necessary to protect the visibility of the file. PostgreSQL won't use it unless permissions are restricted.
```

2024-10-02 07:53 UTC, merged