First pass PGE 16.1 docs
EnterpriseDB/docs pull request #4995
Opened 2023-11-09 17:37 UTC by djw-m

## What Changed?

Added a PGE 16 section with 16.1 release notes.

2023-11-09 17:54 UTC, josh-heyer requested changes
All of the install files should be generated (`npm run install-docs:build; npm run install-docs:deploy`) - to enable this, modify install_template/config.yaml to add `16` to the list of versions for each platform under EDB Postgres Extended Server

2023-11-09 17:54 UTC, josh-heyer commented on product_docs/docs/pge/16/release_notes/index.mdx
> +The EDB Postgres Extended Server documentation describes the latest version of EDB Postgres Extended Server 15,
16 😉

2023-11-10 07:23 UTC, nidhibhammar submitted a review, later dismissed

2023-11-10 07:25 UTC, nidhibhammar commented
Sorry, by mistake, I approved the changes.

2023-11-11 12:48 UTC, djw-m commented on product_docs/docs/pge/16/release_notes/index.mdx
> +The EDB Postgres Extended Server documentation describes the latest version of EDB Postgres Extended Server 15,
Fixed

2023-11-11 16:47 UTC, josh-heyer approved these changes

2023-11-12 09:52 UTC, merged