Edits to postgresql uninstall topic pr5055
EnterpriseDB/docs pull request #5061
Opened 2023-11-30 16:26 UTC by ebgitelman

## What Changed?

2023-11-30 16:33 UTC, djw-m requested changes
You seem to have removed all the images from the uninstallation page.

2023-12-04 14:11 UTC, dwicinas submitted a review, later dismissed

2023-12-05 18:20 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
> +1.  On the Windows Control Panel, open the Uninstall or Change a Program dialog box.
```suggestion
1.  On the Windows Control Panel, open the Uninstall or Change a Program dialog box. 

![The Uninstall or Change a Program dialog box](/installing/images/change_program.png)
```

2023-12-05 18:23 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
>  1. Right-click **PostgreSQL**, and select **Uninstall/Change** from the context menu.
```suggestion
1. Right-click **PostgreSQL**, and select **Uninstall/Change** from the context menu.

![Confirm that you want to uninstall PostgreSQL](/installing/images/uninstalling_postgreSQL_comfirmation.png)
```

2023-12-05 18:24 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
>      - To remove individual components, select **Individual components** and select **Next**. Then, from the list, select the components to uninstall, and select **Next**.
```suggestion
    - To remove individual components, select **Individual components** and select **Next**. Then, from the list, select the components to uninstall, and select **Next**.
    
    ![Select the components to uninstall](/installing/images/select_the_components_to_uninstall.png)
```

2023-12-05 18:25 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
>    A progress bar keeps you informed as PostgreSQL is removed.
```suggestion
  A progress bar keeps you informed as PostgreSQL is removed.
  
  ![Uninstalling PostgreSQL](/installing/images/uninstalling_postgreSQL.png)
```

2023-12-05 18:26 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
>  1.  When the uninstaller completes, select **OK**.
```suggestion
1.  When the uninstaller completes, select **OK**.

![An Info dialog box confirms the uninstallation](/installing/images/uninstallationcomplete.png)
```

2023-12-05 18:35 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
>    The uninstaller opens and asks if you want to uninstall the entire application or individual components.
```suggestion
  The uninstaller opens and asks if you want to uninstall the entire application or individual components. 
  
  ![Remove the entire application or components](/installing/images/remove_the_entire_application_or_components.png)
```

2023-12-05 18:39 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
>      -  To remove individual components, select **Individual components**. Select the components to uninstall, and select **Next** to start uninstalling components.
```suggestion
    -  To remove individual components, select **Individual components**. Select the components to uninstall, and select **Next** to start uninstalling components.
    
![Selecting the components to uninstall](/installing/images/selecting_the_components_to_uninstall.png)
```

2023-12-05 18:40 UTC, ebgitelman commented on advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
>  1.  When the uninstaller completes, select **OK**.
```suggestion
1.  When the uninstaller completes, select **OK**.

![The Uninstallation is completed](/installing/images/mac_uninstallation_completed.png)

```

2023-12-06 12:57 UTC, dwicinas commented
@ebgitelman The step numbers are not working correctly. Probably has to do with how the re-inserted graphics are positioned in the text hierarchy.

2023-12-07 16:51 UTC, merged