MTK - 55.7.0 release branch
EnterpriseDB/docs pull request #5081
Opened 2023-12-11 09:32 UTC by nidhibhammar

## What Changed?

Added release notes as per MTK-1269

2023-12-11 18:34 UTC, mlewandowski-edb requested changes
The changes currently in the PR look good to me; however, the link lable in the Windows section of https://www.enterprisedb.com/docs/migration_toolkit/latest/installing/ page needs to be updated to include:

- Windows Server 2022
- Windows 11

2023-12-12 12:40 UTC, mlewandowski-edb approved these changes

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
> +- the `-copyViaDBLinkOra` option that enables data migration using db_link_ora extension
```suggestion
- The `-copyViaDBLinkOra` option that enables data migration using the db_link_ora extension
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
> +- the Oracle compatible SQL command `CREATE DATABASE LINK`
```suggestion
- The Oracle-compatible SQL command `CREATE DATABASE LINK`
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
> +The Migration Toolkit isn't tested with and doesn't officially support use with Oracle Real Application Clusters (RAC) and Exadata. However, Migration Toolkit might work when it is connected to a sin
```suggestion
The Migration Toolkit isn't tested with and doesn't officially support use with Oracle Real Application Clusters (RAC) and Exadata. However, Migration Toolkit might work when it's connected to a single persistent node. For more information, contact your EDB representative.
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Enhancement  | The Migration Toolkit is now certified to work with all the BigAnimal supported cluster types including the distributed high availability clusters. |
```suggestion
| Enhancement  | The Migration Toolkit is now certified to work with all the BigAnimal supported cluster types including the distributed high-availability clusters. |
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Bug&nbsp;fix | Fixed an issue where user created triggers on the target PostgreSQL or EDB Postgres Advanced Server databases were getting disabled during the data migration phase. [Support ticket #
```suggestion
| Bug&nbsp;fix | Fixed an issue where user-created triggers on the target PostgreSQL or EDB Postgres Advanced Server databases were getting disabled during the data migration phase. [Support ticket #97637] |
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Bug&nbsp;fix | Fixed an issue that caused re-evaluation of the same table with an indefinite loop for table-level parallel loading mode. [Support ticket #96054]|
```suggestion
| Bug&nbsp;fix | Fixed an issue that caused reevaluation of the same table with an indefinite loop for table-level parallel loading mode. [Support ticket #96054]|
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Bug&nbsp;fix | Fixed an issue where a data copy was failing while migrating a source SQL Server table with a case sensitive column name in the EDB Postgres Advanced server target database. |
```suggestion
| Bug&nbsp;fix | Fixed an issue where a data copy was failing while migrating a source SQL server table with a case-sensitive column name in the EDB Postgres Advanced server target database. |
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Bug&nbsp;fix | Fixed an issue where a data copy was failing while migrating a source MySQL table due to a case sensitive table name. |
```suggestion
| Bug&nbsp;fix | Fixed an issue where a data copy was failing while migrating a source MySQL table due to a case-sensitive table name. |
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Bug&nbsp;fix | Fixed an issue where the ``capture_admin`` database system group was getting included when the ``-allgroups`` option was specified for migration from the source EDB Postgres Advanced
```suggestion
| Bug&nbsp;fix | Fixed an issue where the `capture_admin` database system group was getting included when the `-allgroups` option was specified for migration from the source EDB Postgres Advanced Server version 16 database. |
```

2023-12-12 20:35 UTC, ebgitelman commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Bug&nbsp;fix | Fixed an issue for partitioned tables with a SUBPARTITION TEMPLATE clause that caused a partitioned table sub-partitioned by range to fail to migrate. |
```suggestion
| Bug&nbsp;fix | Fixed an issue for partitioned tables with a `SUBPARTITION TEMPLATE` clause that caused a partitioned table sub-partitioned by range to fail to migrate. |
```

2023-12-12 21:16 UTC, mlewandowski-edb submitted a review, later dismissed

2023-12-12 21:21 UTC, mlewandowski-edb submitted a review, later dismissed

2023-12-13 06:58 UTC, nidhibhammar commented on product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5570_rel_notes.mdx
> +| Enhancement  | The Migration Toolkit is now certified to work with all the BigAnimal supported cluster types including the distributed high availability clusters. |
ok @mlewandowski-edb.

2023-12-13 10:38 UTC, djw-m approved these changes
LGTM (Tho am reviewing during a talk at pgconf.eu :) )

2023-12-13 10:50 UTC, merged