DOCS-195:  Readme - update versions node, npm
EnterpriseDB/docs pull request #5463
Opened 2024-03-29 18:01 UTC by piano35-edb

node to 20, npm to 10

2024-03-29 18:04 UTC, josh-heyer requested changes
Missed one spot, otherwise 👍

2024-03-29 18:04 UTC, josh-heyer commented on README.md
>  1. NPM 9 is the package manager we're using for this project.
This line also

2024-03-31 18:06 UTC, josh-heyer approved these changes
👍

2024-04-02 16:04 UTC, djw-m approved these changes
LGTM

2024-04-02 16:05 UTC, merged