Pgd4k/improvements
EnterpriseDB/docs pull request #5697
Opened 2024-05-28 09:39 UTC by gvasquezvargas

## What Changed?

- Added a few minor fixes/improvements
- Tested implementing the usage of environment variables for ease of use 
- Fixed links to be relative

2024-05-29 15:56 UTC, djw-m approved these changes
LGTM

2024-05-31 09:09 UTC, jsilvela requested changes
Mostly optional comments, but the headings for the examples should be revised.

2024-05-31 09:09 UTC, jsilvela commented on product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/assemble_command.mdx
> +## Examples
this seems like a sub-section of "Assembling your command". If so, should be an h3 with three `#`.

2024-05-31 09:09 UTC, jsilvela commented on product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/assemble_command.mdx
> +### Example 1: Setting the environment variables before you run the deployment command
as before, if the Examples section was a subsection, then this should be an h4...

2024-05-31 09:09 UTC, jsilvela commented on product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/assemble_command.mdx
> +    export EDB_SUBSCRIPTION_TOKEN=aaAa1bbbBBcccccC1a1111bB1C1aBbB
seeing as people tend to blaze through instructions, I'd skip the warning of non-realness, and I'd make the token obviously not real.
```suggestion
1.  Set the environment variable to use [your personal token](private_registries/#how-to-retrieve-the-token):

    ```
    export EDB_SUBSCRIPTION_TOKEN=<my-token-for-the-registry>
```

2024-05-31 09:09 UTC, jsilvela commented on product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/assemble_command.mdx
> +    Before running the command, replace the `EDB_SUBSCRIPTION_TOKEN` placeholder.
in the previous example, you set the EDB_SUBSCRIPTION_TOKEN as an env variable.
I'd be consistent in the approach.

2024-05-31 09:09 UTC, jsilvela commented on product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx
> +    export EDB_SUBSCRIPTION_TOKEN=aaAa1bbbBBcccccC1a1111bB1C1aBbB
as my previous comment, I'd suggest setting a clearly-bogus token.

2024-05-31 10:35 UTC, jsilvela approved these changes

2024-05-31 10:45 UTC, merged