WIP: TDE on BigAnimal with Customer Managed Keys
EnterpriseDB/docs pull request #5751
Opened 2024-06-10 16:34 UTC by gvasquezvargas

## What Changed?
 
First draft for https://enterprisedb.atlassian.net/browse/DOCS-724 
Final UI changes are being made as we speak. 
Waiting to be onboarded in Starlight to test the steps myself.

2024-06-12 11:36 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/administering_cluster/projects.mdx
> +1. Complete the remaining fields according to your cloud provider.
I don't think we need provider-specific instructions here, as the UI is very clear. 

The only "difficult" thing is obtaining the key version for the Azure config. We can consider adding a hint/note.

2024-06-12 11:36 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
> +#### Completing the TDE configuration
This is option 1, with the full instructions per cloud provider on how to finalize the configuration.

2024-06-12 11:37 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
> +#### Completing the TDE configuration 2
This is option 2, with simplified instructions per cloud provider on how to finalize the configuration. 
It is less accurate, but we would not have to worry about the instructions becoming outdated without us noticing.

2024-06-12 11:39 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/overview/03_security/index.mdx
> +Enabling TDE using your own encryption key is supported on EDB Postgres Advanced Server and EDB Postgres Extended Server versions 15 and later. Both the key and the cluster must be within the same re
Not sure if they have to be on the same cloud provider... To be clarified with dev.

2024-06-12 11:39 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/overview/03_security/index.mdx
> +|                             | AWS-hosted cluster (BYOA) | GCP-hosted cluster (BYOA) | Azure-hosted cluster (BYOA) | BigAnimal-hosted cluster (BAH) |
Option 1 if cross-provider support is given.

2024-06-12 11:40 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/overview/03_security/index.mdx
> +|                             | AWS-hosted cluster (BYOA) | GCP-hosted cluster (BYOA) | Azure-hosted cluster (BYOA) | BigAnimal-hosted cluster (BAH) |
Option 2 if cluster and key must be on the same provider.

2024-06-12 14:49 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/administering_cluster/projects.mdx
> +   GCP offers the option to configure global keys. If you require a global key, do not select any region.
Waiting on UX improvement. It is possible the UI will contain a "global" selector, which will make this note obsolete.

2024-06-13 15:12 UTC, GabriFedi97 requested changes

2024-06-13 15:12 UTC, GabriFedi97 commented on product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
> +    1. Paste the **Principal** identifier you copied to your clipboard into the `Principal.AWS` field.
We should mention that a new statement needs to be added. The Policy should change from something like this:
```
{
    "Version": "2012-10-17",
    "Id": "key-consolepolicy-3",
    "Statement": [
        {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::142348057180:root"
            },
            "Action": "kms:*",
            "Resource": "*"
        }
    ]
}
```

to something like this:
```
{
    "Version": "2012-10-17",
    "Id": "key-consolepolicy-3",
    "Statement": [
        {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::142348057180:root"
            },
            "Action": "kms:*",
            "Resource": "*"
        },
        {
            "Sid": "Enable TDE on cluster p-k2nxxtndkg",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::142348057180:role/ba-vcvolsnap0ZUPsgZ-us-east-1-p-k2nxxtndkg"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt"
            ],
            "Resource": "*"
        }
    ]
}
```

2024-06-13 15:12 UTC, GabriFedi97 commented on product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
> +    1. Select the key, **Access policies**, and **Create**.
We should mention to set the `Permission model` to `Vault access policy` through the `Access Configuration` section

2024-06-17 08:33 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
> +   Do not to enable TDE when restoring a non-TDE faraway replica cluster.
Same here, I was making a stylistic edit.

Do you think we should be more explicit and tell customers this is not supported? I am not sure if the CLI would do any pre-flight checks and prevent customers from trying to restore a non-TDE faraway replica cluster with TDE enabled. So I think _technically_ they could?

2024-06-17 09:03 UTC, GabriFedi97 commented on product_docs/docs/biganimal/release/using_cluster/05a_deleting_your_cluster.mdx
> +Do not to enable TDE when restoring a non-TDE cluster.
I don't see any value in letting something happen even if we know that will fail for sure, so I think we should prevent that. The UI seems to not be doing that, I'll raise a ticket for the same.

2024-06-17 09:03 UTC, GabriFedi97 commented on product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
> +   Do not to enable TDE when restoring a non-TDE faraway replica cluster.
Same as above

2024-06-17 09:14 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/using_cluster/05a_deleting_your_cluster.mdx
> +Do not to enable TDE when restoring a non-TDE cluster.
@GabriFedi97 gotcha! What do you think we should do here in the docs? Maybe something along the lines of: 
```suggestion
EDB does not support enabling TDE when restoring a non-TDE cluster.
```

2024-06-17 09:15 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
> +   Do not to enable TDE when restoring a non-TDE faraway replica cluster.
And here we could say: 
```suggestion
   EDB does not support enabling TDE when restoring non-TDE faraway replica clusters.
```

2024-06-17 14:22 UTC, GabriFedi97 requested changes

2024-06-17 14:22 UTC, GabriFedi97 commented on product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
> +                         "AWS": "arn:aws:iam::142348057180:role/ba-vcvolsnap0ZUPsgZ-us-east-1-p-k2nxxtndkg"
```suggestion
                         "AWS": "arn:aws:iam::<aws_project_id>:role/<pg_cluster_role>"
```

2024-06-17 14:22 UTC, GabriFedi97 commented on product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
> +                         "AWS": "arn:aws:iam::142348057180:root"
```suggestion
                         "AWS": "arn:aws:iam::<aws_project_id>:root"
```

2024-06-18 08:09 UTC, nidhibhammar approved these changes
LGTM

2024-06-18 08:59 UTC, GabriFedi97 approved these changes

2024-06-25 09:33 UTC, gvasquezvargas commented on product_docs/docs/biganimal/release/administering_cluster/projects.mdx
> +Now, use this TDE key to [create a cluster](/biganimal/release/getting_started/creating_a_cluster/#security).
Add a note above this: 

Note for GCP keys:
If the key you added was created in a different Google Cloud Platform account than the cluster, ensure you enable the [Cloud KMS API](https://cloud.google.com/kms/docs/create-encryption-keys#before-you-begin) in the Google console before assigning it to your cluster in BigAnimal.

2024-06-26 13:04 UTC, dbwagoner commented
I read the new TDE documentation and it looks good to me! Thank you!

2024-06-26 14:01 UTC, merged