Blue/green deployments on BA
EnterpriseDB/docs pull request #5771
Opened 2024-06-13 18:11 UTC by jpe442

## What Changed?

Adds a paper written by Aaron Sonntag and edited by Josh Earlenbaugh on blue/green deployment strategies on big animal.

2024-06-17 17:47 UTC, aaronsonntag commented on product_docs/docs/biganimal/release/using_cluster/07_blue_green.mdx
> +Blue/green deployment is a set of practices that, when applied to a live production system, results in a zero-downtime and low-risk release of software updates[cite O'reilly here Continuous Delivery:
```suggestion
Blue/green deployment is a set of practices that, when applied to a live production system, results in a zero-downtime and low-risk release of software updates[cite O'reilly here Continuous Delivery: Reliable Software Releases Through Build, Test, and Deployment Automation].  The terms *blue* and *green* are abstract labels that differentiate between the two identical production environments—one representing the starting state (in this case blue) and one representing the next state (in this case green). They are chosen to remove any bias that one is correct, better, or the natural destination. We could have chosen green to represent our starting state as well—the color implies nothing.
```

2024-06-17 17:49 UTC, aaronsonntag commented on product_docs/docs/biganimal/release/using_cluster/07_blue_green.mdx
> +The basic pattern is that you take a live production system, which is in your starting state, let's call it blue, and split that into two identical environments: one blue, one green. The terms *blue*
```suggestion
```

2024-06-17 18:20 UTC, aaronsonntag requested changes
Initial edits after transpose to docs repo.

2024-06-17 18:20 UTC, aaronsonntag commented on product_docs/docs/biganimal/release/using_cluster/07_blue_green.mdx
> +By initially upgrading only an initial portion of the system, we can avoid maintenance downtime, improve testing, provide the potential for rollback, and most importantly relieve pressure from these
```suggestion
By initially upgrading only a controlled portion of the system, we can avoid maintenance downtime, improve testing, provide the potential for rollback, and most importantly relieve pressure from these operations, thus improving outcomes.
```

2025-06-06 23:36 UTC, aaronsonntag commented
in case anyone is curious, I'm still referring folksto this PR just about weekly :-D

2025-07-14 09:00 UTC, nidhibhammar commented
We are closing BigAnimal PR's.

2025-07-14 09:00 UTC, closed without merging