Migration Toolkit: SRC_DB_USER role
EnterpriseDB/docs pull request #5798
Opened 2024-06-24 14:17 UTC by gvasquezvargas

## What Changed?

The user does not require DBA privileges for the SRC_DB_USER parameter. This PR updates the documentation to reflect the actual privileges it requires.

2024-06-24 17:24 UTC, mlewandowski-edb requested changes
See comments for a couple of suggested minor updates.

2024-06-24 17:24 UTC, mlewandowski-edb commented on product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
> +-   `SRC_DB_USER` &mdash; Specifies the name of a privileged Oracle user. The Oracle user needs read access to the source database objects you want to migrate. If you want to migrate users/roles and
Change 
> "..., grant the Oracle user SELECT privileges on the following Oracle catalogs:"

to:
> "..., grant the Oracle user SELECT privileges on the following Oracle catalog objects:"

2024-06-24 17:24 UTC, mlewandowski-edb commented on product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
In the rendered page (https://deploy-preview-5798--edb-docs-staging.netlify.app/docs/migration_toolkit/latest/06_building_toolkit.properties_file/#defining-an-oracle-url), the spacing between the catalog object and the next connection parameter (`SRC_DB_PASSWORD`) does not look right.

See:
<img width="911" alt="image" src="https://github.com/EnterpriseDB/docs/assets/63003848/f762a46f-4dd0-4933-86ed-cf417c5c9c97">

2024-06-26 13:27 UTC, djw-m approved these changes
LGTM

2024-06-26 13:37 UTC, merged