TDE refresh: mockup
EnterpriseDB/docs pull request #6130
Opened 2024-10-04 15:18 UTC by gvasquezvargas

## What Changed?

Refreshing the TDE docs.

2024-10-30 16:50 UTC, theadamwright approved these changes

2024-10-31 05:26 UTC, josh-heyer approved these changes
Looks pretty good! Noted a few nits inline.
Also added some redirects.

2024-10-31 17:25 UTC, jpe442 requested changes

2024-10-31 17:26 UTC, jpe442 commented
This is an awesome amount of work and very high quality btw, I just had a few thoughts.

2024-11-01 10:29 UTC, djw-m commented
My only suggestion is moving 

Commands affected by TDE

up the nav so it is above the two commands affected by TDE

and add in initdb to the list as it is also a command affected by TDE and it does seem strange to miss it out from the list.

2024-11-04 09:04 UTC, gvasquezvargas commented on product_docs/docs/tde/15/about/how.mdx
> +### How does TDE encrypt data?
You're right, probably copied it like this from the original page. Updated.

2024-11-04 10:00 UTC, gvasquezvargas commented on product_docs/docs/tde/15/secure_key/index.mdx
> +The key for transparent data encryption (the data key) is generated by `initdb` and stored in a file `pg_encryption/key.bin` under the data directory. This file actually contains several keys that ar
Yes, I think the idea was to call out that among all the keys under the directory, the data encryption key contains a single sequence of random bites. I agree it is kinda confusing.

2024-11-04 10:04 UTC, gvasquezvargas commented on product_docs/docs/tde/15/secure_key/index.mdx
> +After you have chosen a method to protect your key, you can create the wrapping/unwrapping commands.
The user is expected to know, hence the following sentence "Postgres leaves the configuration of the commands to the user". Let me try and make the transition a bit clearer.

Unfortunately, I have not seen guidance on to come up with such a command and we only provide examples with openssl.

2024-11-04 10:19 UTC, gvasquezvargas commented on product_docs/docs/tde/15/secure_key/index.mdx
> +Postgres leaves the configuration of the commands to the user, which allows tailoring the setup to local requirements and integrating with existing key management software or similar. To configure th
I edited both paragraphs to hopefully make this clearer. Let me know what you think.

2024-11-04 15:00 UTC, jpe442 approved these changes
LGTM!

2024-11-04 16:11 UTC, merged