dotNET: added page for nested table support
EnterpriseDB/docs pull request #6226
Opened 2024-11-11 16:47 UTC by gvasquezvargas

## What Changed?

https://enterprisedb.atlassian.net/browse/EC-3206

2024-11-12 15:02 UTC, xfischer requested changes
Thanks a lot @gvasquezvargas !

2024-11-12 15:02 UTC, xfischer commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +```text
can you make this ```csharp
for better syntax coloring ?

2024-11-12 15:02 UTC, xfischer commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +```text
Here text is OK

2024-11-12 16:58 UTC, xfischer commented
LGTM, Thanks a lot Gaby!

2024-11-13 15:52 UTC, gvasquezvargas commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +- The connector resolves all elements of a nested table into `List<object>` elements of a single object type, making the element types consistent in C#.
Hmmm let me use an example to see if I got it: 
So let's say in a nested table called "order", we have object types like `first_name`, `last_name`, and `orderID`. 
When .NET makes a call, it transforms/maps those object types to `List<object>`s (a list of objects). BUT the list items will keep the `first_name`, `last_name`, and `orderID` "metadata"?

2024-11-14 09:13 UTC, gvasquezvargas commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +- The connector resolves all elements of a nested table into `List<object>` elements of a single object type, making the element types consistent in C#.
Gotcha, thanks so much for the explanation! 🙏  In that case, what do you think of this: 
```suggestion
- The connector resolves all items of a nested table into a `List<object>` in C# while maintaining and converting each item's underlying type. For example, `[text1, text1, num1]` becomes `[string1, string2, decimal1]`.
```

2024-11-14 10:27 UTC, xfischer commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +- The connector resolves all elements of a nested table into `List<object>` elements of a single object type, making the element types consistent in C#.
```suggestion
- The connector resolves all rows of a nested table into a `List<object>` in C# while maintaining and converting each column underlying type. For example, a `[text1, text1, num1]` row will be resolved as a `[string, string, decimal]` item in the list.
```

I've replaced "item" by row:

- table of type has rows
- each row has columns
- List<object> has items

If you agree, we can replace that in next bullet list

- If the nested type IS TABLE OF a domain type (int, varchar, decimal, etc.), all the rows will be their C# counterpart according to the [Supported Types and their Mappings](https://www.npgsql.org/doc/types/basic.html#read-mappings).

- If the nested type IS TABLE OF a record or composite type not mapped to a C# class, all rows become a nested List<object> containing as many elements as the record or composite fields, with proper type translation.

- If the nested type IS TABLE OF a record or composite type mapped to a C# class (for example, MyComposite), all rows will be MyComposite instances.

2024-11-18 11:45 UTC, gvasquezvargas commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +- The connector resolves all elements of a nested table into `List<object>` elements of a single object type, making the element types consistent in C#.
Awesome, I made the corrections and I think we are good to go 🥳

2024-11-18 12:10 UTC, xfischer approved these changes

2024-11-19 07:03 UTC, nidhibhammar commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +EDB Postgres Advanced Server supports nested table collection types created with `CREATE TYPE ... AS TABLE OF` statements. The EDB .NET Connector supports output parameters declared as nested tables
```suggestion
EDB Postgres Advanced Server supports nested table collection types created with `CREATE TYPE ... AS TABLE OF` statements. The EDB .NET Connector supports output parameters declared as nested tables out of the box, whether free-standing types or declared inside packages.
```

2024-11-19 07:04 UTC, nidhibhammar commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +- The connector resolves all rows of a nested table into a `List<object>` in C# while maintaining and converting each column's underlying type. For example, a `[text1, text2, num1]` row will be resol
```suggestion
- The connector resolves all nested table rows into a `List<object>` in C# while maintaining and converting each column's underlying type. For example, a `[text1, text2, num1]` row will be resolved as a `[string, string, decimal]` item in the list.
```

2024-11-19 07:05 UTC, nidhibhammar commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +- If the nested type `IS TABLE OF` a domain type (int, varchar, decimal, etc.), all the rows will be their C# counterpart according to the [Supported Types and their Mappings](https://www.npgsql.org/
```suggestion
- If the nested type `IS TABLE OF` is a domain type (int, varchar, decimal, etc.), all the rows will be their C# counterpart according to the [Supported Types and their Mappings](https://www.npgsql.org/doc/types/basic.html#read-mappings).
```

2024-11-19 07:06 UTC, nidhibhammar commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +- If the nested type `IS TABLE OF` a record or composite type **mapped** to a C# class (for example, `MyComposite`), all rows will be `MyComposite` instances.
```suggestion
- If the nested type `IS TABLE OF` is a record or composite type **mapped** to a C# class (for example, `MyComposite`), all rows will be `MyComposite` instances.
```

2024-11-19 07:08 UTC, nidhibhammar commented on product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
> +Nested table types are mapped to `List<object>`s in C#, as it is preferred over `ArrayList`. These lists contain as many elements as the nested table type’s rows. The nested table items are translate
```suggestion
Nested table types are mapped to `List<object>`s in C#, as it is preferred over `ArrayList`. These lists contain as many elements as the nested table type's rows. The nested table items are translated to be compatible with the C# application using the following rules:
```

2024-11-19 07:10 UTC, nidhibhammar approved these changes
I have left some suggestions. You can implement them if you think they make sense.

2024-11-19 08:27 UTC, merged