DOCS-1150 - Updated for aidb 1.1.0
EnterpriseDB/docs pull request #6356
Opened 2024-12-18 11:42 UTC by djw-m

## What Changed?

APIs renamed and refreshed

2025-01-02 15:21 UTC, gvasquezvargas approved these changes
Dropped some minor comments but otherwise LGTM!

2025-01-02 15:21 UTC, gvasquezvargas commented on advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_1.1.0.yml
> +    Management funtions move to use create rather than register and delete rather than drop.
I would mark or highlight the words `create`, `register`, `delete`, `drop`, and `p_`. But only optional.

2025-01-02 15:21 UTC, gvasquezvargas commented on advocacy_docs/edb-postgres-ai/ai-accelerator/retrievers/example.mdx
> +-- Create source test table-- Create source test table
I think there is a copy-paste duplication here?
```suggestion
-- Create source test table
```

2025-01-08 19:04 UTC, noahbaculi requested changes

2025-01-09 09:04 UTC, djw-m commented on advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_2.0.0.yml
> +- relnote: Renaming of functions/arguments
Not that I can tell. No change to create_storage_location that I can see.

2025-01-09 09:54 UTC, djw-m commented on advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_2.0.0.yml
> +- relnote: Renaming of functions/arguments
(There was a lack, in one example, of defining empty mslid and the two JSON blocks which was fixed, but the code didn't change)

2025-01-09 16:30 UTC, iakinsey approved these changes
Approved in relation to consistency with references to OpenAI interfaces.

2025-01-09 17:03 UTC, noahbaculi approved these changes
Approved wrt API naming changes

2025-01-09 18:06 UTC, merged